variables:
    DOCKER_HOST: tcp://docker:2375/
stages:
  - test

unittests:
  stage: test
  image: ghcr.io/nicceboy/multipython:latest
  before_script:
    - apt-get update && apt-get install -y libsqlite3-0
    - echo "Current versions:"
    - source ~/.bashrc
    - python3.6 -V
    - python3.7 -V
    - python3.8 -V
    - python3.9 -V
  services:
  - docker:dind
  script:
    - source ~/.bashrc
  services:
    - docker:dind
  script:
    # - pytest -sv --cov=cincanregistry --cov-report term-missing   
    - source ~/.bashrc && tox -- --cov=cincanregistry tests

